-- Пределы и сроки, прежде зашитые в код, становятся настройками
-- (crates/core/src/model/limits.rs). Значения здесь равны прежним зашитым:
-- обновление не меняет поведение ни у кого. INSERT OR IGNORE, а не REPLACE -
-- значение, уже выбранное пользователем, миграция не трогает.
INSERT OR IGNORE INTO settings(key, value) VALUES
    ('limit_pinned_per_account', '20'),
    ('limit_pinned_visible', '50'),
    ('limit_message_first_page', '100'),
    ('limit_message_page', '500'),
    ('limit_smart_message_page', '500'),
    ('limit_message_memory', '8000'),
    ('limit_sync_failures_before_toast', '3'),
    ('limit_background_sync_minutes', '5'),
    ('limit_rule_groups', '10'),
    ('limit_group_conditions', '10'),
    ('limit_rule_actions', '10'),
    ('limit_quick_steps', '20'),
    ('limit_quick_step_messages', '500'),
    ('limit_manual_run_messages', '5000'),
    ('limit_manual_run_batch', '500'),
    ('limit_undo_send_default', '5'),
    ('limit_undo_send_min', '0'),
    ('limit_undo_send_max', '60'),
    ('limit_recipient_entries', '2000'),
    ('limit_recipient_touches', '50'),
    ('limit_recipient_suggestions', '8'),
    ('limit_oof_silence_days', '7'),
    ('limit_oof_memory_days', '60'),
    ('limit_oof_message_age_hours', '24'),
    ('limit_oof_text_chars', '10000'),
    ('limit_oof_period_days', '366'),
    ('limit_oof_internal_domains', '20'),
    ('limit_done_task_days', '30'),
    ('limit_ignored_conversations', '1000'),
    ('limit_conversation_ids', '1000'),
    ('limit_ignore_return_wait_days', '7'),
    ('limit_sweep_min_days', '1'),
    ('limit_sweep_max_days', '3650'),
    ('limit_purge_batch', '500'),
    ('limit_request_key_days', '30'),
    ('limit_recipient_own_send_days', '30'),
    ('limit_message_traits_days', '30'),
    ('limit_operation_attempts', '8');
