// truemail UI module: smart-rules.js
/* calendar view switch + week/day render */
const calSection=document.getElementById('calSection');
document.querySelectorAll('#calViews button').forEach(b=>b.onclick=()=>{
  document.querySelectorAll('#calViews button').forEach(x=>x.classList.toggle('on',x===b));
  calSection.dataset.cv=b.dataset.cv;
  if(b.dataset.cv==='month')renderCalendarData();else {renderWeekDay(coreCalendarData.events||[]);const wd=localeName(calendarCursor,{weekday:'short'}).replace('.','');document.getElementById('calTitle').textContent=b.dataset.cv==='week'?localeName(calendarCursor,{month:'long',year:'numeric'}):`${wizardLocale==='ru'?wd.slice(0,2):wd.slice(0,3)}, ${localeName(calendarCursor,{day:'numeric',month:'long'})}`;}});
document.querySelectorAll('.calhead > .iconbtn').forEach((button,index)=>button.onclick=()=>{const direction=index===0?-1:1,view=calSection.dataset.cv||'month';if(view==='day')calendarCursor.setDate(calendarCursor.getDate()+direction);else if(view==='week')calendarCursor.setDate(calendarCursor.getDate()+7*direction);else {const day=calendarCursor.getDate();calendarCursor.setDate(1);calendarCursor.setMonth(calendarCursor.getMonth()+direction);calendarCursor.setDate(Math.min(day,new Date(calendarCursor.getFullYear(),calendarCursor.getMonth()+1,0).getDate()));}renderCalendarData();if(view!=='month')document.querySelector(`#calViews button[data-cv="${view}"]`)?.click();});

/* smart folder modal */
const smartOverlay=document.getElementById('smartOverlay');
const smartFields=[
  {id:'sender',ru:'Отправитель',en:'Sender',type:'text'},
  {id:'recipient',ru:'Получатель',en:'Recipient',type:'text'},
  {id:'subject',ru:'Тема',en:'Subject',type:'text'},
  {id:'body',ru:'Текст и предпросмотр',en:'Text and preview',type:'text'},
  {id:'account',ru:'Аккаунт',en:'Account',type:'text'},
  {id:'folder',ru:'Название папки',en:'Folder name',type:'text'},
  {id:'folder_role',ru:'Тип папки',en:'Folder type',type:'enum',values:[['inbox','Входящие','Inbox'],['sent','Отправленные','Sent'],['drafts','Черновики','Drafts'],['archive','Архив','Archive'],['spam','Спам','Spam'],['trash','Корзина','Trash'],['other','Другая','Other']]},
  {id:'read_state',ru:'Прочтение',en:'Read state',type:'enum',values:[['unread','Непрочитано','Unread'],['read','Прочитано','Read']]},
  {id:'importance',ru:'Важность',en:'Importance',type:'enum',values:[['flagged','Важное','Important'],['normal','Обычное','Normal']]},
  {id:'reply_state',ru:'Ответ',en:'Reply state',type:'enum',values:[['answered','На письмо отвечено','Answered'],['unanswered','На письмо не отвечено','Not answered']]},
  {id:'draft_state',ru:'Черновик',en:'Draft state',type:'enum',values:[['draft','Черновик','Draft'],['not_draft','Не черновик','Not a draft']]},
  {id:'attachment',ru:'Вложения',en:'Attachments',type:'enum',values:[['has','Есть вложения','Has attachments'],['none','Нет вложений','No attachments']]},
  {id:'size',ru:'Размер письма',en:'Message size',type:'size'},
  {id:'label',ru:'Метка',en:'Label',type:'text'},
  {id:'date',ru:'Дата письма',en:'Message date',type:'date'},
];
const smartOps={
  contains:['содержит','contains'],not_contains:['не содержит','does not contain'],equals:['равно','equals'],not_equals:['не равно','does not equal'],starts_with:['начинается с','starts with'],ends_with:['заканчивается на','ends with'],
  within_last:['за последние','within last'],older_than:['старше чем','older than'],before:['раньше даты','before'],after:['позже даты','after'],on:['точно в дату','on'],
  greater_than:['больше','greater than'],greater_or_equal:['не меньше','at least'],less_than:['меньше','less than'],less_or_equal:['не больше','at most'],between:['между','between'],
};
const smartUnits=[['minutes','минут','minutes'],['hours','часов','hours'],['days','дней','days'],['weeks','недель','weeks']];
const smartSizeUnits=[['kb','КБ','KB'],['mb','МБ','MB'],['gb','ГБ','GB']];
const legacySmartFields={Отправитель:'sender',Sender:'sender',Получатель:'recipient',Recipient:'recipient',Тема:'subject',Subject:'subject','Текст письма':'body','Message text':'body',Аккаунт:'account',Account:'account',Статус:'read_state',Status:'read_state',Вложение:'attachment',Attachment:'attachment',Метка:'label',Label:'label',Папка:'folder',Folder:'folder',Дата:'date',Date:'date'};
const legacySmartOps={содержит:'contains',contains:'contains','не содержит':'not_contains','does not contain':'not_contains',равно:'equals',equals:'equals'};
const smartIsEnglish=()=>document.documentElement.lang==='en';
const L=(ru,en)=>smartIsEnglish()?en:ru;
const smartLabel=item=>item[smartIsEnglish()?'en':'ru'];
const smartOptionLabel=item=>item[smartIsEnglish()?2:1];
function smartUnitLabel(unit,value){if(smartIsEnglish())return smartOptionLabel(unit);const number=Math.abs(Number(value)||0)%100,last=number%10,forms={minutes:['минута','минуты','минут'],hours:['час','часа','часов'],days:['день','дня','дней'],weeks:['неделя','недели','недель']}[unit[0]];return number>=11&&number<=19?forms[2]:last===1?forms[0]:last>=2&&last<=4?forms[1]:forms[2];}
function smartField(id){return smartFields.find(field=>field.id===id)||smartFields[0];}
function smartOperators(field){return field.type==='text'?['contains','not_contains','equals','not_equals','starts_with','ends_with']:field.type==='date'?['within_last','older_than','before','after','on']:field.type==='size'?['greater_than','greater_or_equal','less_than','less_or_equal','equals','between']:['equals','not_equals'];}
function normalizeSmartCondition(condition={}){
  let field=legacySmartFields[condition.f]||condition.f||'sender',operator=legacySmartOps[condition.o]||condition.o||'contains',value=condition.v??'';
  if(field==='status'){field='read_state';}if(field==='attachment'){value=value==='yes'?'has':value==='no'?'none':value;}
  if(field==='read_state'&&value==='seen')value='read';if(field==='read_state'&&value==='not_seen')value='unread';
  const definition=smartField(field),allowed=smartOperators(definition);if(!allowed.includes(operator))operator=allowed[0];
  return {f:definition.id,o:operator,v:String(value),...(definition.type==='date'&&['within_last','older_than'].includes(operator)?{u:condition.u||'hours'}:{}),...(definition.type==='size'?{u:condition.u||'mb',v2:String(condition.v2??'')}:{})};
}
function normalizeSmartGroup(group={}){const source=Array.isArray(group)?group:group.conditions;return {logic:Array.isArray(group)?'all':group.logic==='any'?'any':'all',conditions:(Array.isArray(source)?source:[]).map(normalizeSmartCondition)};}
function renderConditionValue(row,condition){
  const field=smartField(condition.f),host=row.querySelector('.cond-value');host.className='cond-value';host.innerHTML='';
  if(field.type==='enum'){
    const select=document.createElement('select');select.className='cond-input';select.innerHTML=field.values.map(item=>`<option value="${item[0]}">${escapeHtml(smartOptionLabel(item))}</option>`).join('');select.value=field.values.some(item=>item[0]===condition.v)?condition.v:field.values[0][0];host.appendChild(select);
  }else if(field.type==='date'&&['within_last','older_than'].includes(condition.o)){
    host.classList.add('relative-date');const input=document.createElement('input');input.className='cond-input';input.type='number';input.min='1';input.step='1';input.value=/^\d+(?:\.\d+)?$/.test(condition.v)?condition.v:'24';const unit=document.createElement('select');unit.className='cond-unit';unit.innerHTML=smartUnits.map(item=>`<option value="${item[0]}">${escapeHtml(smartOptionLabel(item))}</option>`).join('');unit.value=smartUnits.some(item=>item[0]===condition.u)?condition.u:'hours';host.append(input,unit);
  }else if(field.type==='size'){
    host.classList.add('relative-date');const input=document.createElement('input');input.className='cond-input';input.type='number';input.min='0';input.step='0.1';input.placeholder=smartIsEnglish()?'size':'размер';input.value=/^\d+(?:\.\d+)?$/.test(condition.v)?condition.v:'10';host.appendChild(input);if(condition.o==='between'){const second=document.createElement('input');second.className='cond-max';second.type='number';second.min='0';second.step='0.1';second.placeholder=smartIsEnglish()?'to':'до';second.value=/^\d+(?:\.\d+)?$/.test(condition.v2)?condition.v2:'50';host.appendChild(second);}const unit=document.createElement('select');unit.className='cond-unit';unit.innerHTML=smartSizeUnits.map(item=>`<option value="${item[0]}">${escapeHtml(smartOptionLabel(item))}</option>`).join('');unit.value=smartSizeUnits.some(item=>item[0]===condition.u)?condition.u:'mb';host.appendChild(unit);
  }else{
    const input=document.createElement('input');input.className='cond-input';input.type=field.type==='date'?'date':'text';input.placeholder=smartIsEnglish()?'value':'значение';input.value=condition.v||'';host.appendChild(input);
  }
  host.querySelectorAll('input,select').forEach(control=>{control.addEventListener('input',updateSmartPreview);control.addEventListener('change',updateSmartPreview);});
}
function readConditionRow(row){return normalizeSmartCondition({f:row.querySelector('.cond-field').value,o:row.querySelector('.cond-op').value,v:row.querySelector('.cond-input')?.value||'',v2:row.querySelector('.cond-max')?.value||'',u:row.querySelector('.cond-unit')?.value});}
function validSmartCondition(source){const condition=normalizeSmartCondition(source),field=smartField(condition.f);if(field.type==='enum')return field.values.some(item=>item[0]===condition.v);if(field.type==='date'&&['within_last','older_than'].includes(condition.o))return Number(condition.v)>0&&smartUnits.some(item=>item[0]===condition.u);if(field.type==='date')return /^\d{4}-\d{2}-\d{2}$/.test(condition.v);if(field.type==='size')return Number(condition.v)>=0&&smartSizeUnits.some(item=>item[0]===condition.u)&&(condition.o!=='between'||Number(condition.v2)>Number(condition.v));return Boolean(condition.v.trim());}
function condRow(source={}){const condition=normalizeSmartCondition(typeof source==='object'?source:{f:source});const r=document.createElement('div');r.className='cond';
  r.innerHTML=`<select class="cond-field">${smartFields.map(field=>`<option value="${field.id}">${escapeHtml(smartLabel(field))}</option>`).join('')}</select><select class="cond-op"></select><div class="cond-value"></div><button type="button" class="del iconbtn" title="${smartIsEnglish()?'Delete condition':'Удалить условие'}"><i data-i="trash"></i></button>`;
  const fieldSelect=r.querySelector('.cond-field'),operatorSelect=r.querySelector('.cond-op');fieldSelect.value=condition.f;
  const rebuildOperator=(selected)=>{const field=smartField(fieldSelect.value),operators=smartOperators(field);operatorSelect.innerHTML=operators.map(id=>`<option value="${id}">${escapeHtml(smartOps[id][smartIsEnglish()?1:0])}</option>`).join('');operatorSelect.value=operators.includes(selected)?selected:operators[0];renderConditionValue(r,{...condition,f:field.id,o:operatorSelect.value,v:field.id===condition.f?condition.v:'',u:condition.u});updateSmartPreview();};
  fieldSelect.onchange=()=>rebuildOperator();operatorSelect.onchange=()=>{const current=readConditionRow(r);renderConditionValue(r,current);updateSmartPreview();};rebuildOperator(condition.o);
  r.querySelector('.del').onclick=()=>{r.remove();updateSmartPreview();};renderIcons(r);return r;}
let editingSmartIndex=null,selectedSmartIcon='star';
function renumberConditionGroups(){document.querySelectorAll('#conds .cond-group').forEach((group,index)=>{group.querySelector('.cond-group-title').textContent=`${smartIsEnglish()?'Group':'Группа'} ${index+1}`;group.querySelector('.cond-group-remove').classList.toggle('hidden',document.querySelectorAll('#conds .cond-group').length===1);});}
function conditionGroup(source={conditions:[{}]}){const state=normalizeSmartGroup(source),group=document.createElement('div');group.className='cond-group';group.dataset.logic=state.logic;
  group.innerHTML=`<div class="cond-group-head"><span class="cond-group-title"></span><div class="logic"><button type="button" data-l="all">${smartIsEnglish()?'All (AND)':'Все (И)'}</button><button type="button" data-l="any">${smartIsEnglish()?'Any (OR)':'Любое (ИЛИ)'}</button></div><button type="button" class="iconbtn cond-group-remove" title="${smartIsEnglish()?'Delete group':'Удалить группу'}"><i data-i="trash"></i></button></div>`;
  group.querySelectorAll('.logic button').forEach(button=>{button.classList.toggle('on',button.dataset.l===state.logic);button.onclick=()=>{group.dataset.logic=button.dataset.l;group.querySelectorAll('.logic button').forEach(item=>item.classList.toggle('on',item===button));updateSmartPreview();};});
  (state.conditions.length?state.conditions:[{}]).forEach(condition=>group.appendChild(condRow(condition)));group.querySelector('.cond-group-remove').onclick=()=>{group.remove();renumberConditionGroups();updateSmartPreview();};renderIcons(group);return group;}
function readSmartGroups(){return [...document.querySelectorAll('#conds .cond-group')].map(group=>({logic:group.dataset.logic==='any'?'any':'all',conditions:[...group.querySelectorAll('.cond')].map(readConditionRow)})).filter(group=>group.conditions.length);}
function editorSmartFolder(){return {groups:readSmartGroups()};}
function updateSmartPreview(){const preview=document.getElementById('smartPreview');if(!preview)return;try{preview.textContent=String(smartRowsForFolder(editorSmartFolder()).length);}catch(_){preview.textContent='0';}}
function openSmart(index=null){editingSmartIndex=index;const c=document.getElementById('conds');c.innerHTML='';const item=index===null?null:smartFolders[index];document.querySelector('#smartOverlay .mh h3').textContent=item?L('Изменить умную папку','Edit smart folder'):L('Новая умная папка','New smart folder');document.getElementById('smartCreate').lastChild.textContent=item?L(' Сохранить',' Save'):L(' Создать умную папку',' Create smart folder');document.getElementById('smartDelete').classList.toggle('hidden',!item||item.builtin);document.getElementById('smartName').value=item?.t||'';selectedSmartIcon=item?.i||'star';updateSmartIconButton();(item?.groups?.length?item.groups:[{conditions:[{}]}]).forEach(group=>c.appendChild(conditionGroup(group)));renumberConditionGroups();smartOverlay.classList.add('open');updateSmartPreview();loadCompleteSmartCoverage(index??-1);}
function closeSmart(){smartOverlay.classList.remove('open');}
document.getElementById('addSmart').onclick=(e)=>{e.stopPropagation();openSmart();};
document.getElementById('addCond').onclick=()=>{document.querySelector('#conds .cond-group:last-child')?.appendChild(condRow());updateSmartPreview();};
document.getElementById('addCondGroup').onclick=()=>{document.getElementById('conds').appendChild(conditionGroup());renumberConditionGroups();updateSmartPreview();};
document.getElementById('smartClose').onclick=closeSmart;
document.getElementById('smartCancel').onclick=closeSmart;
document.getElementById('smartCreate').onclick=()=>{const name=document.getElementById('smartName').value.trim(),groups=readSmartGroups();if(!name){showToast(L('Введите название умной папки','Enter a smart folder name'));return;}if(!groups.length||groups.some(group=>!group.conditions.length||group.conditions.some(condition=>!validSmartCondition(condition)))){showToast(L('Заполните все условия умной папки','Fill in all smart folder conditions'));return;}const previous=editingSmartIndex===null?null:smartFolders[editingSmartIndex],item={...(previous||{}),id:previous?.id||`custom-${Date.now()}`,builtin:Boolean(previous?.builtin),i:selectedSmartIcon,t:name,on:previous?.on??true,groups};if(editingSmartIndex===null)smartFolders.push(item);else smartFolders[editingSmartIndex]=item;renderSmartManagement();bindSmartNavigation();persistSmartFolders().then(()=>{if(currentSmartIndex===editingSmartIndex)filterSmart(editingSmartIndex);}).catch(error=>showToast(error.message||String(error)));closeSmart();};
document.getElementById('smartDelete').onclick=async()=>{const folder=editingSmartIndex===null?null:smartFolders[editingSmartIndex];if(!folder||folder.builtin||!await confirmAction(L(`Удалить умную папку «${folder.t}»?`,`Delete the smart folder "${folder.t}"?`)))return;const activeId=smartFolders[currentSmartIndex]?.id;smartFolders.splice(editingSmartIndex,1);renderSmartManagement();bindSmartNavigation();persistSmartFolders().catch(error=>showToast(error.message||String(error)));closeSmart();if(activeId===folder.id)filterSmart(0);};
smartOverlay.onclick=e=>{if(e.target===smartOverlay)closeSmart();};
const smartIconKeys=Object.keys(ic).filter(key=>!['chevR','chevL','up','down','back','dots','grip'].includes(key)).slice(0,50);
const smartIconsEl=document.getElementById('smartIcons');smartIconsEl.innerHTML=smartIconKeys.map(key=>`<span class="ic-pick" data-sel="${key}" title="${key}"><i data-i="${key}"></i></span>`).join('');renderIcons(smartIconsEl);
function updateSmartIconButton(){const i=document.querySelector('#smartIconButton i');i.dataset.i=selectedSmartIcon;i.innerHTML=ic[selectedSmartIcon]||ic.star;document.querySelectorAll('#smartIcons .ic-pick').forEach(p=>p.classList.toggle('on',p.dataset.sel===selectedSmartIcon));}
document.getElementById('smartIconButton').onclick=()=>smartIconsEl.classList.toggle('hidden');document.querySelectorAll('#smartIcons .ic-pick').forEach(p=>p.onclick=()=>{selectedSmartIcon=p.dataset.sel;updateSmartIconButton();smartIconsEl.classList.add('hidden');});

/* toolbar customizer */
const tbActions=[
  {k:'reply',t:'Ответить',en:'Reply',on:true},{k:'replyall',t:'Ответить всем',en:'Reply all',on:true},{k:'forward',t:'Переслать',en:'Forward',on:true},
  {k:'archive',t:'В архив',en:'Archive',on:true},{k:'trash',t:'Удалить',en:'Delete',on:true},{k:'spam',t:'В спам',en:'Spam',on:false},{k:'snooze',t:'Отложить',en:'Snooze',on:false},
  {k:'unread',t:'Непрочитанное',en:'Mark unread',i:'inbox',on:false},{k:'unsub',t:'Отписаться',en:'Unsubscribe',on:false},{k:'print',t:'Печать',en:'Print',on:false}];
const tbLabel=a=>smartIsEnglish()&&a.en?a.en:a.t;
const tbList=document.getElementById('tbList');
tbActions.forEach(a=>{const r=document.createElement('div');r.className='tbrow'+(a.on?'':' off');r.draggable=true;r.dataset.action=a.k;
  r.dataset.labels='text';r.innerHTML=`<span class="grip"><i data-i="grip"></i></span><i data-i="${a.i||a.k}"></i><span class="nm">${escapeHtml(tbLabel(a))}</span><button type="button" class="btn sm action-label-mode" title="${smartIsEnglish()?'Toggle label':'Переключить подпись'}">${smartIsEnglish()?'Icon + text':'Значок + текст'}</button>
    <span class="ord"><button class="iconbtn" data-dir="up"><i data-i="up"></i></button><button class="iconbtn" data-dir="down"><i data-i="down"></i></button></span>
    <div class="toggle${a.on?' on':''}"></div>`;
  renderIcons(r);
  const save=()=>{applyToolbar();persistToolbar();};
  r.querySelector('[data-dir="up"]').onclick=()=>{const p=r.previousElementSibling;if(p)tbList.insertBefore(r,p);save();};
  r.querySelector('[data-dir="down"]').onclick=()=>{const n=r.nextElementSibling;if(n)tbList.insertBefore(n,r);save();};
  r.querySelector('.action-label-mode').onclick=event=>{event.stopPropagation();r.dataset.labels=r.dataset.labels==='icons'?'text':'icons';event.currentTarget.textContent=r.dataset.labels==='icons'?(smartIsEnglish()?'Icon only':'Только значок'):(smartIsEnglish()?'Icon + text':'Значок + текст');save();};
  r.querySelector('.toggle').onclick=(e)=>{e.stopPropagation();const t=e.currentTarget;t.classList.toggle('on');r.classList.toggle('off',!t.classList.contains('on'));save();};
  tbList.appendChild(r);});
let draggedToolbarRow=null;tbList.addEventListener('dragstart',e=>{draggedToolbarRow=e.target.closest('.tbrow');});tbList.addEventListener('dragover',e=>{e.preventDefault();const row=e.target.closest('.tbrow');if(row&&draggedToolbarRow&&row!==draggedToolbarRow){const rect=row.getBoundingClientRect();tbList.insertBefore(draggedToolbarRow,e.clientY<rect.top+rect.height/2?row:row.nextSibling);}});tbList.addEventListener('drop',()=>{applyToolbar();persistToolbar();});
tbList.addEventListener('pointerdown',event=>{const grip=event.target.closest('.grip'),row=grip?.closest('.tbrow');if(!row||event.button!==0)return;event.preventDefault();draggedToolbarRow=row;row.classList.add('pointer-dragging');grip.setPointerCapture(event.pointerId);});
tbList.addEventListener('pointermove',event=>{if(!draggedToolbarRow)return;const target=document.elementFromPoint(event.clientX,event.clientY)?.closest('.tbrow');if(!target||target===draggedToolbarRow||target.parentElement!==tbList)return;const rect=target.getBoundingClientRect();tbList.insertBefore(draggedToolbarRow,event.clientY<rect.top+rect.height/2?target:target.nextSibling);});
tbList.addEventListener('pointerup',event=>{if(!draggedToolbarRow)return;event.target.closest('.grip')?.releasePointerCapture?.(event.pointerId);draggedToolbarRow.classList.remove('pointer-dragging');draggedToolbarRow=null;applyToolbar();persistToolbar();});
function toolbarState(){return {actions:[...tbList.children].map(row=>({key:row.dataset.action,visible:!row.classList.contains('off'),labels:row.dataset.labels||'text'})),align:document.querySelector('#toolbarAlign .on')?.dataset.align||'left'};}
function persistToolbar(){window.tm?.setSetting('toolbar_layout',JSON.stringify(toolbarState())).catch(console.error);}
function applyToolbar(){const state=toolbarState(),bar=document.querySelector('.thread .actions');if(!bar)return;bar.classList.toggle('toolbar-right',state.align==='right');bar.querySelectorAll('[data-toolbar-generated]').forEach(el=>el.remove());const anchor=bar.querySelector('.sp');state.actions.filter(action=>action.visible).forEach(action=>{const meta=tbActions.find(a=>a.k===action.key);if(!meta)return;const button=document.createElement('button');button.className=`${action.key==='reply'?'btn primary':'btn'}${action.labels==='icons'?' toolbar-action-icons':''}`;button.dataset.toolbarGenerated='1';button.dataset.act=action.key;button.title=tbLabel(meta);button.innerHTML=`<i data-i="${meta.i||action.key}"></i><span>${escapeHtml(tbLabel(meta))}</span>`;renderIcons(button);bar.insertBefore(button,anchor);});bar.querySelectorAll(':scope > button:not([data-toolbar-generated]):not([data-toolbar-persistent])').forEach(button=>button.classList.add('toolbar-original-hidden'));
  // Меню "Ещё" показывает только те действия, что скрыты из панели - без дублей.
  const menuDyn=document.getElementById('threadMenuDynamic');
  if(menuDyn){menuDyn.innerHTML='';state.actions.filter(action=>!action.visible).forEach(action=>{const meta=tbActions.find(a=>a.k===action.key);if(!meta)return;const button=document.createElement('button');button.type='button';button.dataset.toolbarMenu=action.key;button.innerHTML=`<i data-i="${meta.i||action.key}"></i><span>${escapeHtml(tbLabel(meta))}</span>`;menuDyn.appendChild(button);});renderIcons(menuDyn);const sep=document.getElementById('threadMenuDynSep');if(sep)sep.style.display=menuDyn.children.length?'':'none';}}
document.querySelectorAll('#toolbarAlign button').forEach(button=>button.onclick=()=>{button.parentElement.querySelectorAll('button').forEach(x=>x.classList.toggle('on',x===button));applyToolbar();persistToolbar();});
applyToolbar();
function embeddedUnsubscribeUrl(message){
  if(!message?.body_html)return null;
  const parsed=new DOMParser().parseFromString(message.body_html,'text/html');
  const unsubscribeWords=/(?:unsubscribe|opt[\s_-]*out|remove[\s_-]*(?:me|email)|отпис(?:аться|ка|ать)|отказаться[\s\S]{0,20}рассылк)/i;
  for(const link of parsed.querySelectorAll('a[href]')){
    const href=link.getAttribute('href')?.trim()||'';
    if(!/^https?:\/\//i.test(href))continue;
    const context=link.closest('p,li,td,div')?.textContent||'';
    let searchable=`${link.textContent||''} ${context} ${link.getAttribute('title')||''} ${link.getAttribute('aria-label')||''} ${href}`;
    try{searchable+=` ${decodeURIComponent(href)}`;}catch(_){/* Keep matching against the original malformed URL. */}
    if(unsubscribeWords.test(searchable))return href;
  }
  return null;
}
function selectedOrActiveMessageIds(){return selectedMessageIds.size?[...selectedMessageIds]:activeMessage?[activeMessage.id]:[];}
function nextMondayMorning(){const value=new Date();const days=(8-value.getDay())%7||7;value.setDate(value.getDate()+days);value.setHours(9,0,0,0);return value;}
function openSnoozeDialog(){const ids=selectedOrActiveMessageIds();if(!ids.length){showToast(L('Сначала выберите письмо','Select a message first'));return;}
  const overlay=document.createElement('div');overlay.className='overlay open';overlay.innerHTML=`<div class="modal compact-modal snooze-modal"><div class="mh"><i data-i="snooze"></i><h3>${L('Отложить письмо','Snooze message')}</h3><button class="iconbtn x" type="button"><i data-i="close"></i></button></div><div class="mb"><div class="snooze-presets"><button class="btn" data-offset="hour">${L('Через час','In one hour')}</button><button class="btn" data-offset="tomorrow">${L('Завтра в 09:00','Tomorrow at 09:00')}</button><button class="btn" data-offset="monday">${L('В понедельник в 09:00','Monday at 09:00')}</button></div><label class="template-field">${L('Другое время','Custom time')}<input class="inp snooze-custom" type="datetime-local"></label></div><div class="mf"><span class="sp"></span><button class="btn snooze-cancel">${L('Отмена','Cancel')}</button><button class="btn primary snooze-apply">${L('Отложить','Snooze')}</button></div></div>`;
  document.body.appendChild(overlay);renderIcons(overlay);const close=()=>overlay.remove();const custom=overlay.querySelector('.snooze-custom');const initial=new Date(Date.now()+60*60*1000);initial.setSeconds(0,0);custom.value=new Date(initial.getTime()-initial.getTimezoneOffset()*60000).toISOString().slice(0,16);
  const apply=async date=>{try{await window.tm.snoozeMessages(ids,date.toISOString());clearMessageSelection();activeMessage=null;activeFullMessage=null;await window.reloadCoreData();close();showToast(L(`Отложено писем: ${ids.length}`,`Snoozed messages: ${ids.length}`),L('Отменить','Undo'),async()=>{await window.tm.unsnoozeMessages(ids);await window.reloadCoreData();});}catch(error){showToast(error.message||String(error));}};
  overlay.querySelector('[data-offset="hour"]').onclick=()=>apply(new Date(Date.now()+60*60*1000));overlay.querySelector('[data-offset="tomorrow"]').onclick=()=>{const d=new Date();d.setDate(d.getDate()+1);d.setHours(9,0,0,0);apply(d);};overlay.querySelector('[data-offset="monday"]').onclick=()=>apply(nextMondayMorning());overlay.querySelector('.snooze-apply').onclick=()=>{const d=new Date(custom.value);if(Number.isNaN(d.getTime())||d<=new Date()){showToast(L('Выберите будущее время','Choose a future time'));return;}apply(d);};overlay.querySelectorAll('.x,.snooze-cancel').forEach(button=>button.onclick=close);overlay.onclick=event=>{if(event.target===overlay)close();};custom.focus();}
async function exportActiveMessageEml(){if(!activeMessage){showToast(L('Сначала выберите письмо','Select a message first'));return;}const safe=(activeMessage.subject||'message').replace(/[<>:"/\\|?*\x00-\x1f]/g,'_').trim().slice(0,100)||'message';try{const path=await window.tm.saveFileDialog(`${safe}.eml`);if(!path)return;await window.tm.exportMessageEml(activeMessage.id,path);showToast(L('Письмо сохранено в .eml','Message saved as .eml'));}catch(error){showToast(error.message||String(error));}}
async function executeToolbarAction(action){if(['reply','replyall','forward'].includes(action)){openComposerForMessage(action);return;}if(['archive','trash','spam'].includes(action)){performMessageAction(action);return;}if(action==='snooze'){openSnoozeDialog();return;}if(action==='unread'){if(activeMessage){await window.tm?.markSeen(activeMessage.id,false);await window.reloadCoreData?.();showToast(L('Письмо отмечено непрочитанным','Message marked as unread'));}return;}if(action==='print'){const frame=document.querySelector('.mail-html-frame');if(frame?.contentWindow)frame.contentWindow.print();else window.print();return;}if(action==='unsub'){const uns=activeFullMessage?.unsubscribe;
  if(uns?.one_click_url){showToast(L('Отправляю запрос на отписку…','Sending unsubscribe request…'));const fallback=()=>window.tm?.openExternal(uns.http||uns.one_click_url).catch(error=>showToast(error.message||String(error)));try{const status=await window.tm.unsubscribeOneClick(uns.one_click_url);if(status>=200&&status<300)showToast(L('Готово: вы отписаны от рассылки (сервер подтвердил, код '+status+')','Done: you have been unsubscribed (server confirmed, code '+status+')'));else{showToast(L('Сервер отписки ответил кодом '+status+'. Открываю страницу отписки…','The unsubscribe server responded with code '+status+'. Opening the unsubscribe page…'));fallback();}}catch(error){showToast(L('Автоотписка не удалась: '+(error.message||error)+'. Открываю страницу…','Automatic unsubscribe failed: '+(error.message||error)+'. Opening the page…'));fallback();}return;}
  const target=uns?.http||embeddedUnsubscribeUrl(activeFullMessage);if(target){try{await window.tm.openExternal(target);showToast(L('Открыл страницу отписки в браузере — завершите отписку там','Opened the unsubscribe page in your browser — finish there'));}catch(error){showToast(error.message||String(error));}return;}
  const mailto=uns?.mailto;if(mailto){resetComposer();setRecipients('compTo',[String(mailto).replace(/^mailto:/i,'').split('?')[0]]);document.getElementById('compSubj').value=L('Отписаться','Unsubscribe');showView('composeView');showToast(L('Отправьте это письмо, чтобы отписаться','Send this message to unsubscribe'));return;}
  showToast(L('В письме нет ссылки для автоматической отписки','This message has no automatic unsubscribe link'));}}
document.querySelector('.thread .actions').addEventListener('click',e=>{const button=e.target.closest('[data-toolbar-generated]');if(button)executeToolbarAction(button.dataset.act);});
const threadMoreButton=document.getElementById('threadMoreButton'),threadMoreMenu=document.getElementById('threadMoreMenu');
function closeThreadMore(){threadMoreMenu.classList.remove('open');threadMoreButton.setAttribute('aria-expanded','false');}
threadMoreButton.onclick=event=>{event.stopPropagation();const open=threadMoreMenu.classList.toggle('open');threadMoreButton.setAttribute('aria-expanded',String(open));};
threadMoreMenu.onclick=async event=>{const toolbarItem=event.target.closest('[data-toolbar-menu]');if(toolbarItem){closeThreadMore();executeToolbarAction(toolbarItem.dataset.toolbarMenu);return;}const button=event.target.closest('[data-thread-action]');if(!button)return;closeThreadMore();const action=button.dataset.threadAction;if(action==='settings'){showView('settingsView');setSection('toolbar');return;}if(action==='rules'){showView('settingsView');setSection('rules');return;}if(action==='raw'){openRawViewer(activeMessage?.id);return;}if(action==='export-eml'){exportActiveMessageEml();return;}if(action==='create-rule'){openRuleEditor(activeMessage);return;}if(action==='unread'){if(activeMessage){await window.tm?.markSeen(activeMessage.id,false);await window.reloadCoreData?.();showToast(L('Письмо отмечено непрочитанным','Message marked as unread'));}return;}if(['archive','trash'].includes(action))performMessageAction(action);};
document.addEventListener('click',event=>{if(!threadMoreMenu.contains(event.target)&&event.target!==threadMoreButton)closeThreadMore();});

/* Server-side mail actions driven by locally stored, editable rules. */
const ruleEditor=document.getElementById('ruleEditor'),ruleAccount=document.getElementById('ruleAccount'),ruleAction=document.getElementById('ruleAction'),ruleTarget=document.getElementById('ruleTarget');
function ruleAccountFolders(){const accountId=Number(ruleAccount.value);return coreFolders.filter(folder=>folder.account_id===accountId);}
function populateRuleTargets(selectedFolderId=null){
  const previous=selectedFolderId??(Number(ruleTarget.value)||null);
  ruleTarget.innerHTML=ruleAccountFolders().map(folder=>`<option value="${folder.id}">${escapeHtml(folderTitle(folder))}</option>`).join('');
  if(previous&&ruleTarget.querySelector(`option[value="${previous}"]`))ruleTarget.value=String(previous);
}
function updateRuleActionFields(){
  const moving=ruleAction.value==='move';document.querySelector('.rule-target-field').classList.toggle('hidden',!moving);
  if(moving&&ruleAccount.value==='all'){ruleAccount.value=String(coreAccounts[0]?.id||'');populateRuleTargets();}
}
function openRuleEditor(source=null,rule=null){
  showView('settingsView');setSection('rules');editingRuleId=rule?.id??null;ruleEditor.classList.remove('hidden');
  document.getElementById('ruleEditorTitle').textContent=rule?L('Изменить правило','Edit rule'):L('Новое правило','New rule');
  ruleAccount.innerHTML=`<option value="all">${L('Все аккаунты','All accounts')}</option>`+coreAccounts.map(account=>`<option value="${account.id}">${escapeHtml(account.email)}</option>`).join('');
  const sourceEmail=source?.from?.email||'',sourceAccount=source?.account_id||coreAccounts[0]?.id||'all';ruleEditor.dataset.sourceSender=sourceEmail;ruleEditor.dataset.sourceSubject=source?.subject||'';
  document.getElementById('ruleName').value=rule?.name||(sourceEmail?L(`Письма от ${sourceEmail}`,`Mail from ${sourceEmail}`):'');document.getElementById('ruleField').value=rule?.field||'sender';document.getElementById('ruleOperator').value=rule?.operator||'contains';document.getElementById('ruleValue').value=rule?.value||sourceEmail;ruleAccount.value=String(rule?.account_id??sourceAccount);ruleAction.value=rule?.action||'move';populateRuleTargets(rule?.folder_id);updateRuleActionFields();document.getElementById('ruleExisting').checked=false;document.getElementById('ruleDelete').classList.toggle('hidden',!rule);document.getElementById('ruleName').focus();
}
function closeRuleEditor(){ruleEditor.classList.add('hidden');editingRuleId=null;}
function ruleDescription(rule){
  const en=smartIsEnglish(),fields=en?{sender:'Sender',subject:'Subject'}:{sender:'Отправитель',subject:'Тема'},operators=en?{contains:'contains',equals:'equals'}:{contains:'содержит',equals:'равно'},actions=en?{archive:'archive',spam:'move to spam',trash:'delete'}:{archive:'в архив',spam:'в спам',trash:'удалить'};const account=rule.account_id?coreAccounts.find(item=>item.id===rule.account_id)?.email:L('все аккаунты','all accounts');let action=actions[rule.action];if(rule.action==='move')action=L(`в папку «${folderTitle(coreFolders.find(folder=>folder.id===rule.folder_id))}»`,`to folder "${folderTitle(coreFolders.find(folder=>folder.id===rule.folder_id))}"`);return `${fields[rule.field]} ${operators[rule.operator]} «${rule.value}» → ${action||L('действие не настроено','action not set')} · ${account||L('аккаунт удалён','account removed')}`;
}
function renderRulesList(){
  const list=document.getElementById('rulesList');list.innerHTML='';if(!mailRules.length){list.innerHTML=`<p class="rule-empty">${L('Правил пока нет.','No rules yet.')}</p>`;return;}
  mailRules.forEach(rule=>{const row=document.createElement('div');row.className='rule-row';row.innerHTML=`<div class="toggle${rule.enabled!==false?' on':''}" role="switch"></div><div><div class="rule-row-title"></div><div class="rule-row-description"></div></div><button type="button" class="btn sm"><i data-i="edit"></i>${L('Изменить','Edit')}</button>`;row.querySelector('.rule-row-title').textContent=rule.name;row.querySelector('.rule-row-description').textContent=ruleDescription(rule);row.querySelector('.toggle').onclick=async()=>{try{await window.tm.setMailRuleEnabled(rule.id,!rule.enabled);await reloadMailRules();}catch(error){showToast(error.message||String(error));}};row.querySelector('button').onclick=()=>openRuleEditor(null,rule);list.appendChild(row);});renderIcons(list);
}
async function reloadMailRules(){mailRules=await window.tm.listMailRules();renderRulesList();}
window.reloadMailRules=reloadMailRules;
document.getElementById('ruleNew').onclick=()=>openRuleEditor();document.getElementById('ruleCancel').onclick=closeRuleEditor;ruleAccount.onchange=()=>populateRuleTargets();ruleAction.onchange=updateRuleActionFields;document.getElementById('ruleField').onchange=event=>{if(editingRuleId!==null)return;const value=event.target.value==='subject'?ruleEditor.dataset.sourceSubject:ruleEditor.dataset.sourceSender;if(value)document.getElementById('ruleValue').value=value;};
document.getElementById('ruleSave').onclick=async()=>{const name=document.getElementById('ruleName').value.trim(),value=document.getElementById('ruleValue').value.trim(),accountValue=ruleAccount.value,action=ruleAction.value,folderId=action==='move'?Number(ruleTarget.value):null;if(!name||!value){showToast(L('Заполните название и значение условия','Fill in the name and condition value'));return;}if(action==='move'&&!folderId){showToast(L('Выберите папку назначения','Choose a destination folder'));return;}const existing=mailRules.find(rule=>rule.id===editingRuleId),applyExisting=document.getElementById('ruleExisting').checked,rule={id:existing?.id||`rule-${Date.now()}`,name,field:document.getElementById('ruleField').value,operator:document.getElementById('ruleOperator').value,value,account_id:accountValue==='all'?null:Number(accountValue),action,folder_id:folderId,enabled:existing?.enabled??true};try{await window.tm.saveMailRule(rule,applyExisting);await reloadMailRules();closeRuleEditor();showToast(L('Правило сохранено','Rule saved'));setTimeout(()=>window.reloadCoreData?.().catch(console.error),350);}catch(error){showToast(error.message||String(error));}};
document.getElementById('ruleDelete').onclick=async()=>{const rule=mailRules.find(item=>item.id===editingRuleId);if(!rule||!await confirmAction(L(`Удалить правило «${rule.name}»?`,`Delete the rule "${rule.name}"?`)))return;try{await window.tm.deleteMailRule(rule.id);await reloadMailRules();closeRuleEditor();}catch(error){showToast(error.message||String(error));}};

/* smart folders management list */
const builtinSmartDefaults=[
  {id:'all-inbox',builtin:true,i:'inbox',t:'Все входящие',on:true,groups:[{logic:'all',conditions:[{f:'folder_role',o:'equals',v:'inbox'}]}]},
  {id:'all-important',builtin:true,i:'star',t:'Все важные',on:true,groups:[{logic:'all',conditions:[{f:'importance',o:'equals',v:'flagged'}]}]},
  {id:'all-sent',builtin:true,i:'send',t:'Все отправленные',on:true,groups:[{logic:'all',conditions:[{f:'folder_role',o:'equals',v:'sent'}]}]},
  {id:'all-drafts',builtin:true,i:'draft',t:'Все черновики',on:true,groups:[{logic:'all',conditions:[{f:'folder_role',o:'equals',v:'drafts'}]},{logic:'all',conditions:[{f:'draft_state',o:'equals',v:'draft'}]}]},
  {id:'last-24-hours',builtin:true,i:'cal',t:'Сегодня (за 24 часа)',on:true,groups:[{logic:'all',conditions:[{f:'date',o:'within_last',v:'24',u:'hours'}]}]},
  {id:'all-unread',builtin:true,i:'search',t:'Непрочитанные (все)',on:true,groups:[{logic:'all',conditions:[{f:'read_state',o:'equals',v:'unread'}]}]},
  {id:'with-attachments',builtin:true,i:'paperclip',t:'С вложениями',on:true,groups:[{logic:'all',conditions:[{f:'attachment',o:'equals',v:'has'}]}]},
  {id:'awaiting-my-reply',builtin:true,i:'flag',t:'Ждут ответа',on:true,groups:[{logic:'all',conditions:[{f:'folder_role',o:'equals',v:'inbox'},{f:'reply_state',o:'equals',v:'unanswered'}]}]},
];
const cloneSmart=value=>JSON.parse(JSON.stringify(value));
function normalizedSmartFolders(saved){
  if(!Array.isArray(saved))return cloneSmart(builtinSmartDefaults);const unused=new Map(builtinSmartDefaults.map(folder=>[folder.id,folder])),result=[];
  saved.forEach((raw,index)=>{if(!raw||typeof raw!=='object')return;let base=builtinSmartDefaults.find(folder=>folder.id===raw.id||folder.t===raw.t);if(!base&&index<8)base=builtinSmartDefaults.find(folder=>unused.has(folder.id)&&folder.i===raw.i);if(!base&&index<8)base=builtinSmartDefaults.find(folder=>unused.has(folder.id));if(base)unused.delete(base.id);
    const groups=Array.isArray(raw.groups)&&raw.groups.some(group=>(Array.isArray(group)?group:group?.conditions)?.length)?raw.groups.map(normalizeSmartGroup):cloneSmart(base?.groups||[]);result.push({...cloneSmart(base||{}),...raw,id:base?.id||raw.id||`custom-${Date.now()}-${index}`,builtin:Boolean(base||raw.builtin),on:raw.on!==false,groups});});
  unused.forEach(folder=>result.push(cloneSmart(folder)));return result;
}
const smartFolders=cloneSmart(builtinSmartDefaults);
function smartConditionDescription(source){const condition=normalizeSmartCondition(source),field=smartField(condition.f),operator=smartOps[condition.o]?.[smartIsEnglish()?1:0]||condition.o;let value=condition.v;
  if(field.values)value=smartOptionLabel(field.values.find(item=>item[0]===condition.v)||[condition.v,condition.v,condition.v]);else if(field.type==='date'&&['within_last','older_than'].includes(condition.o)){const unit=smartUnits.find(item=>item[0]===condition.u)||smartUnits[1];value=`${condition.v} ${smartUnitLabel(unit,condition.v)}`;}else if(field.type==='size'){const unit=smartSizeUnits.find(item=>item[0]===condition.u)||smartSizeUnits[1],label=smartOptionLabel(unit);value=condition.o==='between'?`${condition.v}–${condition.v2} ${label}`:`${condition.v} ${label}`;}else if(field.type==='text')value=`«${value}»`;
  return `${smartLabel(field)} ${operator} ${value}`;
}
function smartFolderDescription(folder){return (folder.groups||[]).map(source=>{const group=normalizeSmartGroup(source),joiner=group.logic==='any'?(smartIsEnglish()?' OR ':' ИЛИ '):(smartIsEnglish()?' AND ':' И ');return group.conditions.map(smartConditionDescription).join(joiner);}).filter(Boolean).join(smartIsEnglish()?'  • OR •  ':'  • ИЛИ •  ');}
const smartListEl=document.getElementById('smartList');
const builtinSmartTitles={
  'all-inbox':{ru:'Все входящие',en:'All inboxes'},
  'all-important':{ru:'Все важные',en:'All important'},
  'all-sent':{ru:'Все отправленные',en:'All sent'},
  'all-drafts':{ru:'Все черновики',en:'All drafts'},
  'last-24-hours':{ru:'Сегодня (за 24 часа)',en:'Today (last 24 hours)'},
  'all-unread':{ru:'Непрочитанные (все)',en:'Unread (all)'},
  'with-attachments':{ru:'С вложениями',en:'With attachments'},
  'awaiting-my-reply':{ru:'Ждут ответа',en:'Awaiting reply'},
};
function smartFolderTitle(folder){if(folder&&folder.builtin&&builtinSmartTitles[folder.id])return builtinSmartTitles[folder.id][smartIsEnglish()?'en':'ru'];return folder?.t||'';}
function messagesTitle(){return smartIsEnglish()?'Messages':'Письма';}
function smartFolderToCore(folder,index){return {id:String(folder.id),name:folder.t||'',icon:folder.i||null,is_builtin:Boolean(folder.builtin),enabled:folder.on!==false,sort_order:index,groups:(folder.groups||[]).map(group=>{const normalized=normalizeSmartGroup(group);return {logic:normalized.logic,conditions:normalized.conditions.map(condition=>({field:condition.f,op:condition.o,value:String(condition.v??''),unit:condition.u||null,value2:condition.v2||null}))};})};}
function smartFolderFromCore(folder){return {id:String(folder.id),builtin:Boolean(folder.is_builtin),i:folder.icon||'star',t:folder.name||'',on:folder.enabled!==false,groups:(folder.groups||[]).map(group=>({logic:group.logic==='any'?'any':'all',conditions:(group.conditions||[]).map(condition=>({f:condition.field,o:condition.op,v:String(condition.value??''),...(condition.unit?{u:condition.unit}:{}),...(condition.value2!=null?{v2:String(condition.value2)}:{})}))}))};}
function persistSmartFolders(){return window.tm?.saveSmartFolders(smartFolders.map(smartFolderToCore))||Promise.resolve();}
function moveSmartFolder(from,to){if(to<0||to>=smartFolders.length)return;const activeId=smartFolders[currentSmartIndex]?.id;[smartFolders[from],smartFolders[to]]=[smartFolders[to],smartFolders[from]];if(activeId)currentSmartIndex=smartFolders.findIndex(folder=>folder.id===activeId);renderSmartManagement();bindSmartNavigation();persistSmartFolders().catch(error=>showToast(error.message||String(error)));}
function renderSmartManagement(){smartListEl.innerHTML='';smartFolders.forEach((a,index)=>{const r=document.createElement('div');r.className='tbrow smart-list-row'+(a.on?'':' off');
  r.innerHTML=`<span class="grip"><i data-i="grip"></i></span><i data-i="${a.i}"></i><span class="smart-name"><span class="nm"></span><span class="smart-summary"></span></span><button class="btn sm edit-sf">${smartIsEnglish()?'Edit':'Изменить'}</button><span class="ord"><button class="iconbtn" data-dir="up"><i data-i="up"></i></button><button class="iconbtn" data-dir="down"><i data-i="down"></i></button></span><div class="toggle${a.on?' on':''}"></div>`;
  r.querySelector('.nm').textContent=smartFolderTitle(a);r.querySelector('.smart-summary').textContent=smartFolderDescription(a);renderIcons(r);
  r.querySelector('[data-dir="up"]').onclick=()=>moveSmartFolder(index,index-1);
  r.querySelector('[data-dir="down"]').onclick=()=>moveSmartFolder(index,index+1);
  r.querySelector('.edit-sf').onclick=()=>openSmart(index);
  r.querySelector('.toggle').onclick=(e)=>{e.stopPropagation();const t=e.currentTarget;t.classList.toggle('on');a.on=t.classList.contains('on');r.classList.toggle('off',!a.on);bindSmartNavigation();persistSmartFolders().catch(error=>showToast(error.message||String(error)));};
  smartListEl.appendChild(r);});}
renderSmartManagement();
document.getElementById('smartNew2').onclick=()=>openSmart();
function bindSmartNavigation(){document.querySelectorAll('.custom-smart').forEach(row=>row.remove());const nav=document.querySelector('.nav'),accountLabel=nav.querySelector('[data-navlabel="accounts"]')||[...nav.querySelectorAll('.navlabel')].find(label=>label.textContent.includes('Аккаунты'));smartFolders.forEach((folder,index)=>{let row=folder.builtin?nav.querySelector(`[data-smart-id="${folder.id}"]`):null;if(!row){row=document.createElement('button');row.type='button';row.className='navitem custom-smart';row.dataset.nav='mail';row.innerHTML='<i></i><span class="smart-label"></span>';}
    row.dataset.smartIndex=index;row.dataset.smartId=folder.id;const icon=row.querySelector('i');icon.dataset.i=folder.i;icon.innerHTML=ic[folder.i]||ic.star;const label=row.querySelector('.smart-label');label.textContent=smartFolderTitle(folder);row.style.display=folder.on?'':'none';row.onclick=()=>{clearMessageSelection();goMail();document.querySelectorAll('.navitem').forEach(item=>item.classList.remove('active'));row.classList.add('active');filterSmart(index);};accountLabel.before(row);});}
bindSmartNavigation();
ctxsmart.querySelector('[data-smart-action="open"]').onclick=()=>filterSmart(+ctxsmart.dataset.index);
ctxsmart.querySelector('[data-smart-action="edit"]').onclick=()=>openSmart(+ctxsmart.dataset.index);
ctxsmart.querySelector('[data-smart-action="settings"]').onclick=()=>{showView('settingsView');setSection('smart');};

const auxOverlay=document.getElementById('auxOverlay'),eventForm=document.getElementById('eventForm'),contactForm=document.getElementById('contactForm');
let editingEvent=null,editingContact=null;
function closeAuxEditor(){auxOverlay.classList.remove('open');editingEvent=null;editingContact=null;}
function fillAccountSelect(select,selected){select.innerHTML='';coreAccounts.forEach(account=>{const option=document.createElement('option');option.value=account.id;option.textContent=account.email;select.appendChild(option);});if(selected!=null)select.value=String(selected);}
function fillCalendarSelect(accountId,selected){const select=document.getElementById('eventCalendar');select.innerHTML='';(coreCalendarData.calendars||[]).filter(calendar=>calendar.account_id===Number(accountId)).forEach(calendar=>{const option=document.createElement('option');option.value=calendar.id;option.textContent=calendar.name;select.appendChild(option);});if(selected!=null)select.value=String(selected);}
function localDateValue(value){const date=parseDavDate(value);if(!date)return '';const p=n=>String(n).padStart(2,'0');return `${date.getFullYear()}-${p(date.getMonth()+1)}-${p(date.getDate())}T${p(date.getHours())}:${p(date.getMinutes())}`;}
function remoteDateValue(value,allDay){if(allDay)return String(value).slice(0,10);const date=new Date(value);return Number.isNaN(date.getTime())?value:date.toISOString();}
function eventLineValues(value){return String(value||'').split(/[\n,]/).map(item=>item.trim()).filter(Boolean);}
function attendeeLabel(attendee){return attendee.name?`${attendee.name} <${attendee.email}>`:attendee.email;}
function eventAttendeesFromForm(source){const existing=new Map((source?.attendees||[]).map(attendee=>[attendee.email.toLocaleLowerCase(),attendee]));return String(document.getElementById('eventAttendees').value||'').split(/\n/).map(value=>value.trim()).filter(Boolean).map(value=>{const match=value.match(/^(.*?)\s*<([^<>]+)>$/),email=(match?.[2]||value).trim(),previous=existing.get(email.toLocaleLowerCase());return{email,name:match?.[1]?.trim()||previous?.name||null,role:previous?.role||'REQ-PARTICIPANT',partstat:previous?.partstat||'NEEDS-ACTION',rsvp:previous?.rsvp??true};});}
function eventInputFromForm(source){const allDay=document.getElementById('eventAllDay').checked,rruleMode=document.getElementById('eventRecurrence').value;return{summary:document.getElementById('eventSummary').value.trim(),description:document.getElementById('eventDescription').value.trim()||null,location:document.getElementById('eventLocation').value.trim()||null,dtstart:remoteDateValue(document.getElementById('eventStart').value,allDay),dtend:document.getElementById('eventEnd').value?remoteDateValue(document.getElementById('eventEnd').value,allDay):null,all_day:allDay,attendees:eventAttendeesFromForm(source),alarms:eventLineValues(document.getElementById('eventAlarms').value).map(Number).filter(value=>Number.isFinite(value)&&value>=0).map(trigger_minutes=>{const previous=(source?.alarms||[]).find(alarm=>alarm.trigger_minutes===trigger_minutes);return{trigger_minutes,action:previous?.action||'DISPLAY'};}),rrule:rruleMode==='custom'?document.getElementById('eventRrule').value.trim()||null:rruleMode||null,recurrence_id:source?.recurrence_id||null,exdates:eventLineValues(document.getElementById('eventExdates').value).join(',')||null,rdates:eventLineValues(document.getElementById('eventRdates').value).join(',')||null,timezone:document.getElementById('eventTimezone').value.trim()||null,transp:document.getElementById('eventTransp').value||null,class:document.getElementById('eventClass').value||null,categories:eventLineValues(document.getElementById('eventCategories').value),url:document.getElementById('eventUrl').value.trim()||null,organizer:document.getElementById('eventOrganizer').value.trim()||null,sequence:Number(source?.sequence||0)};}
function eventInputFromModel(source,dtstart,dtend){return{summary:source.summary,description:source.description||null,location:source.location||null,dtstart,dtend,all_day:Boolean(source.all_day),attendees:source.attendees||[],alarms:source.alarms||[],rrule:source.rrule||null,recurrence_id:source.recurrence_id||null,exdates:source.exdates||null,rdates:source.rdates||null,timezone:source.timezone||null,transp:source.transp||null,class:source.class||null,categories:source.categories||[],url:source.url||null,organizer:source.organizer||null,sequence:Number(source.sequence||0)};}
function setEventRecurrenceMode(rrule){const standard=['FREQ=DAILY','FREQ=WEEKLY','FREQ=MONTHLY','FREQ=YEARLY'],mode=!rrule?'':standard.includes(rrule)?rrule:'custom';document.getElementById('eventRecurrence').value=mode;document.getElementById('eventRrule').value=rrule||'';document.querySelector('.event-rrule-custom').classList.toggle('hidden',mode!=='custom');}
document.getElementById('eventRecurrence').onchange=event=>document.querySelector('.event-rrule-custom').classList.toggle('hidden',event.target.value!=='custom');
function setAuxMode(mode){const isEvent=mode==='event';eventForm.classList.toggle('hidden',!isEvent);contactForm.classList.toggle('hidden',isEvent);document.getElementById('auxTitle').textContent=isEvent?(editingEvent?L('Изменить событие / задачу','Edit event / task'):L('Новое событие / задача','New event / task')):(editingContact?L('Изменить контакт','Edit contact'):L('Новый контакт','New contact'));document.getElementById('auxIcon').innerHTML=isEvent?ic.cal:ic.people;}
function openEventEditor(event=null){editingEvent=event;editingContact=null;setAuxMode('event');fillAccountSelect(document.getElementById('eventAccount'),event?coreCalendarData.calendars.find(calendar=>calendar.id===event.calendar_id)?.account_id:coreAccounts[0]?.id);fillCalendarSelect(document.getElementById('eventAccount').value,event?.calendar_id);document.getElementById('eventAccount').disabled=Boolean(event);document.getElementById('eventCalendar').disabled=Boolean(event);document.getElementById('eventSummary').value=event?.summary||'';const start=event?.dtstart?localDateValue(event.dtstart):localDateValue(new Date(Math.ceil(Date.now()/1800000)*1800000).toISOString());document.getElementById('eventStart').value=start;document.getElementById('eventEnd').value=event?.dtend?localDateValue(event.dtend):localDateValue(new Date(new Date(start).getTime()+3600000).toISOString());document.getElementById('eventAllDay').checked=Boolean(event?.all_day)||/^\d{4}-\d{2}-\d{2}$/.test(event?.dtstart||'')||/^\d{8}$/.test(event?.dtstart||'');document.getElementById('eventLocation').value=event?.location||'';document.getElementById('eventDescription').value=event?.description||'';setEventRecurrenceMode(event?.rrule);document.getElementById('eventExdates').value=String(event?.exdates||'').split(',').join('\n');document.getElementById('eventRdates').value=String(event?.rdates||'').split(',').join('\n');document.getElementById('eventAttendees').value=(event?.attendees||[]).map(attendeeLabel).join('\n');document.getElementById('eventAlarms').value=(event?.alarms||[]).map(alarm=>alarm.trigger_minutes).join('\n');document.getElementById('eventOrganizer').value=event?.organizer||'';document.getElementById('eventTimezone').value=event?.timezone||Intl.DateTimeFormat().resolvedOptions().timeZone||'';document.getElementById('eventTransp').value=event?.transp||'opaque';document.getElementById('eventClass').value=event?.class||'public';document.getElementById('eventCategories').value=(event?.categories||[]).join(', ');document.getElementById('eventUrl').value=event?.url||'';document.querySelector('.event-advanced').open=Boolean(event&&(event.rrule||event.exdates||event.rdates||event.attendees?.length||event.alarms?.length||event.organizer||event.categories?.length||event.url));document.getElementById('eventDelete').classList.toggle('hidden',!event);document.getElementById('eventStatus').textContent='';auxOverlay.classList.add('open');document.getElementById('eventSummary').focus();}
function openContactEditor(contact=null){editingContact=contact;editingEvent=null;setAuxMode('contact');fillAccountSelect(document.getElementById('contactAccount'),contact?.account_id||coreAccounts[0]?.id);document.getElementById('contactAccount').disabled=Boolean(contact);document.getElementById('contactDisplayName').value=contact?.display_name||'';document.getElementById('contactFirstName').value=contact?.first_name||'';document.getElementById('contactLastName').value=contact?.last_name||'';document.getElementById('contactOrganization').value=contact?.organization||'';document.getElementById('contactEmails').value=(contact?.emails||[]).map(item=>item.email).join('\n');document.getElementById('contactDelete').classList.toggle('hidden',!contact);document.getElementById('contactStatus').textContent='';auxOverlay.classList.add('open');document.getElementById('contactDisplayName').focus();}
document.getElementById('eventAccount').onchange=e=>fillCalendarSelect(e.target.value);
document.getElementById('newEventBtn').onclick=()=>openEventEditor();
document.getElementById('newContactBtn').onclick=()=>openContactEditor();
document.getElementById('auxClose').onclick=closeAuxEditor;document.getElementById('eventCancel').onclick=closeAuxEditor;document.getElementById('contactCancel').onclick=closeAuxEditor;
auxOverlay.addEventListener('click',event=>{if(event.target===auxOverlay)closeAuxEditor();});
eventForm.onsubmit=async event=>{event.preventDefault();const status=document.getElementById('eventStatus'),input=eventInputFromForm(editingEvent);status.textContent=L('Сохраняю на сервере…','Saving to the server…');status.dataset.kind='';try{if(editingEvent)await window.tm.updateEvent(editingEvent.id,input);else await window.tm.createEvent(Number(document.getElementById('eventAccount').value),Number(document.getElementById('eventCalendar').value),input);await window.reloadCoreData();closeAuxEditor();showToast(L('Событие сохранено и синхронизировано','Event saved and synced'));}catch(error){status.textContent=String(error);status.dataset.kind='error';}};
document.getElementById('eventDelete').onclick=async()=>{if(!editingEvent||!confirm(L('Удалить событие или задачу на сервере?','Delete this event or task on the server?')))return;const status=document.getElementById('eventStatus');status.textContent=L('Удаляю…','Deleting…');try{await window.tm.deleteEvent(editingEvent.id);await window.reloadCoreData();closeAuxEditor();showToast(L('Удалено на сервере','Deleted on the server'));}catch(error){status.textContent=String(error);status.dataset.kind='error';}};
contactForm.onsubmit=async event=>{event.preventDefault();const status=document.getElementById('contactStatus'),input={display_name:document.getElementById('contactDisplayName').value.trim(),first_name:document.getElementById('contactFirstName').value.trim()||null,last_name:document.getElementById('contactLastName').value.trim()||null,organization:document.getElementById('contactOrganization').value.trim()||null,emails:document.getElementById('contactEmails').value.split(/[\n,;]/).map(value=>value.trim()).filter(Boolean)};status.textContent=L('Сохраняю на сервере…','Saving to the server…');status.dataset.kind='';try{if(editingContact)await window.tm.updateContact(editingContact.id,input);else await window.tm.createContact(Number(document.getElementById('contactAccount').value),input);await window.reloadCoreData();closeAuxEditor();showToast(L('Контакт сохранён и синхронизирован','Contact saved and synced'));}catch(error){status.textContent=String(error);status.dataset.kind='error';}};
document.getElementById('contactDelete').onclick=async()=>{if(!editingContact||!confirm(L('Удалить контакт на сервере?','Delete this contact on the server?')))return;const status=document.getElementById('contactStatus');status.textContent=L('Удаляю…','Deleting…');try{await window.tm.deleteContact(editingContact.id);await window.reloadCoreData();closeAuxEditor();showToast(L('Контакт удалён на сервере','Contact deleted on the server'));}catch(error){status.textContent=String(error);status.dataset.kind='error';}};
calSection.addEventListener('click',e=>{if(window.calendarDropJustHappened)return;const item=e.target.closest('.ev,.wk-ev');if(!item)return;e.stopPropagation();const event=coreCalendarData.events.find(value=>value.id===Number(item.dataset.eventId));if(event)openEventEditor(event);});
window.moveCalendarEvent=async(eventId,sourceValue,targetValue)=>{const source=coreCalendarData.events.find(value=>value.id===Number(eventId));if(!source)return;const parseTarget=value=>{const match=String(value).match(/^(\d{4})-(\d{2})-(\d{2})$/);return match?new Date(+match[1],+match[2]-1,+match[3]):parseDavDate(value);},sourceOccurrence=parseDavDate(sourceValue)||parseDavDate(source.dtstart),target=parseTarget(targetValue);if(!sourceOccurrence||!target)return;if(/^\d{4}-\d{2}-\d{2}$/.test(String(targetValue))&&!source.all_day)target.setHours(sourceOccurrence.getHours(),sourceOccurrence.getMinutes(),sourceOccurrence.getSeconds(),sourceOccurrence.getMilliseconds());const delta=target-sourceOccurrence,start=parseDavDate(source.dtstart),end=parseDavDate(source.dtend);if(!start)return;const movedStart=new Date(start.getTime()+delta),movedEnd=end?new Date(end.getTime()+delta):null,pad=value=>String(value).padStart(2,'0'),dateOnly=value=>`${value.getFullYear()}-${pad(value.getMonth()+1)}-${pad(value.getDate())}`,input=eventInputFromModel(source,source.all_day?dateOnly(movedStart):movedStart.toISOString(),movedEnd?(source.all_day?dateOnly(movedEnd):movedEnd.toISOString()):null);try{await window.tm.updateEvent(source.id,input);await window.reloadCoreData();showToast(L('Событие перенесено','Event moved'));}catch(error){showToast(error.message||String(error));}};

